// Generated by NeptuneCoffee 0.3.0
// path: geometry.js
define([
  './geometry/namespace',
  './geometry/box',
  './geometry/circle',
  './geometry/solids'
], function(Geometry, Box, Circle, Solids) {
  if (typeof Box == 'function') {Geometry.Box = Box; Box.namespace = Geometry;}
  if (typeof Circle == 'function') {Geometry.Circle = Circle; Circle.namespace = Geometry;}
  if (typeof Solids == 'function') {Geometry.Solids = Solids; Solids.namespace = Geometry;}
  return Geometry;
});