// Generated by NeptuneCoffee 0.2.0
define([
  './geometry/namespace',
  './geometry/box',
  './geometry/circle',
  './geometry/solids'
], function(Geometry, Box, Circle) {
  Geometry.Box = Box; Box.namespace = Geometry;
  Geometry.Circle = Circle; Circle.namespace = Geometry;
  return Geometry;
});
