// Generated by NeptuneCoffee 0.0.2
define([
  './geometry/namespace'
], function(Geometry) {
  Neptune = (function() {
    function Neptune() {}
    return Neptune;
  })();
  Neptune.Geometry = Geometry; Geometry.namespace = Neptune;
  return Neptune;
});
