// Generated by NeptuneCoffee 0.2.2
// path: geometry/solids/namespace.js
define([], function() {
  var Solids = (function() {
    function Solids() {}
    return Solids;
  })();
  return Solids;
});
