// Generated by NeptuneCoffee 0.2.4
// path: geometry/namespace.js
define([
  './solids/namespace'
], function(Solids) {
  var Geometry = (function() {
    function Geometry() {}
    return Geometry;
  })();
  Geometry.Solids = Solids; Solids.namespace = Geometry;
  return Geometry;
});