// Generated by NeptuneCoffee 0.0.2
define([
  './solids/namespace'
], function(Solids) {
  Geometry = (function() {
    function Geometry() {}
    return Geometry;
  })();
  Geometry.Solids = Solids; Solids.namespace = Geometry;
  return Geometry;
});
