// Generated by NeptuneCoffee 0.3.0
// path: geometry/solids.js
define([
  './solids/namespace',
  './solids/cone'
], function(Solids, Cone) {
  if (typeof Cone == 'function') {Solids.Cone = Cone; Cone.namespace = Solids;}
  return Solids;
});