// Generated by NeptuneCoffee 0.2.0
define([
  './solids/namespace',
  './solids/cone'
], function(Solids, Cone) {
  if (typeof Cone == 'function') {Solids.Cone = Cone; Cone.namespace = Solids;}
  return Solids;
});
